osx_image: xcode10.2
language: objective-c
jobs:
  include:
    - stage: Testing
      before_install:
        - gem install cocoapods
      script:
        - pod install
        - xcodebuild test -workspace Example.xcworkspace -scheme Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X'
    - stage: deploying to cocoapods
      before_install:
        - echo $TRAVIS_TAG
        - export CURRENT_VERSION=$TRAVIS_TAG
        - gem install cocoapods
      script:
        - pod lib lint --allow-warnings
        - pod trunk push --allow-warnings
      if: tag IS present